### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by AdedayoOpeyemi** [VanessaAoki/AwesomeBooks#2]
Hi Vannesa,

This is a great job you and your partner have done on this.

- [x] The only recommended change the team sees is to separate your code and have all your Javascript code in the .js file.

Keep it up

**Comment by VanessaAoki** [comment]
@AdedayoOpeyemi hi,

Suggestion implemented!

Thanks so much for the feedback
